meta_product_name: "Mathieu Leblond"
meta_title: "Mathieu Leblond - Curriculum Vitea"
meta_description: "Retrouvez le CV de Mathieu Leblond"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
