meta_product_name: "Mathieu Leblond"
meta_title: "Mathieu Leblond - Curriculum Vitea"
meta_description: "Retrouvez le CV de Mathieu Leblond"
meta_image: "cover.jpg" # should exist in `app/assets/images/`

